[package]
name = "async_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["blocking"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
